#!/usr/bin/env ruby

while true
  File.open('/proc/acpi/ibm/thermal', 'r') do |f|
    system "echo level #{(f.read.split(' ')[1].to_i > 60 ? 'auto' : '1')} > /proc/acpi/ibm/fan"
  end
  sleep 120
end
